name: Desplegando en nginx ec2
on:
 push:
   branches:
     - main  # Change to your default branch


jobs:
 deploy:
   runs-on: ubuntu-latest


   steps:
     - name: Checkout repository
       uses: actions/checkout@v4

     - name: Set up Terraform
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_version: 1.10.0 # Cambia a la versión que estés usando

     - name: Set up AWS CLI
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
     - name: Initialize Terraform
       run: terraform init
 
     - name: Terraform Plan
       id: terraform-plan
       run: terraform plan -out=tfplan
 
     - name: Apply Terraform Plan
       if: success()
       run: terraform apply -input=false -auto-approve tfplan
 
     - name: Handle Terraform Errors
       if: failure()
       run: |
           echo "Terraform Plan failed. Attempting to destroy resources..."
           terraform destroy -auto-approve || echo "Destroy failed. Manual cleanup might be required."